---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    repository: "https://kubernetes.github.io/ingress-nginx/"
    name: ingress-nginx
    version: 3.30.0
  values:
    tolerations: 
      - key: "dedicated"
        operator: "Equal"
        value: "ingress"
        effect: "NoSchedule"
    labels:
      type: "ingress"

