---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: aws-node-termination-handler
  namespace: kube-system
spec:
  chart:
    repository: "https://aws.github.io/eks-charts/"
    name: aws-node-termination-handler
    version: 0.15.0
  values:
    enableSpotInterruptionDraining: "true"
    enableRebalanceMonitoring: "true"
    enableScheduledEventDraining: "true"
