---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux-app-mbeham
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*
spec:
  releaseName: flux-app-mbeham
  chart:
    git: git@github.com:mbeham/mank8s_helm
    path: generic
    ref: master
  values:
    image:
      repository: mbeham/flux_demo
      tag: '2.0.0'
      pullPolicy: Always
    replicaCount: 2
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      path: /
      hosts:
      - flux-mbeham.mank8s.jambit.space
      tls:
      - hosts:
        - flux-mbeham.mank8s.jambit.space
        secretName: flux-mbeham-cert
    nodeSelector: {}
    tolerations: []
    affinity: {}
